let questions=[];let lastResultText='';
function cfg(k,f){return (window.QUIZ_CONFIG&&window.QUIZ_CONFIG[k])||f}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function norm(s){return String(s).trim().toLowerCase().replace(/\s+/g,'')}
async function loadQuestions(){try{let r=await fetch('questions.json',{cache:'no-store'});questions=await r.json();render()}catch(e){document.getElementById('quizContainer').innerHTML='<p class="note">Could not load questions.</p>'}}
function render(){let c=document.getElementById('quizContainer');c.innerHTML='';questions.forEach((q,i)=>{let ans='';if(q.type==='input'){ans='<label>Your answer</label><input type="text" id="answer-'+i+'">'}else{ans=(q.options||[]).map((o,j)=>'<label class="option"><input type="radio" name="answer-'+i+'" value="'+esc(o)+'"> '+String.fromCharCode(65+j)+'. '+esc(o)+'</label>').join('')}c.innerHTML+='<div class="question"><h2>Question '+(i+1)+'</h2><p>'+esc(q.question)+'</p>'+ans+'<div id="feedback-'+i+'" class="feedback"></div></div>'})}
function getAnswer(i){let q=questions[i];if(q.type==='input')return document.getElementById('answer-'+i).value;let x=document.querySelector('input[name="answer-'+i+'"]:checked');return x?x.value:''}
function isCorrect(a,b){return norm(a)===norm(b)}
async function gradeQuiz(e){e.preventDefault();let score=0,wrong=[],details=[];questions.forEach((q,i)=>{let a=getAnswer(i);let ok=isCorrect(a,q.answer);let f=document.getElementById('feedback-'+i);if(ok){score++;f.className='feedback correct';f.textContent='Correct! '+(q.explanation||'')}else{wrong.push(i+1);f.className='feedback wrong';f.textContent='Not correct. Correct answer: '+q.answer+'. '+(q.explanation||'')}details.push('Q'+(i+1)+': '+q.question+'\nStudent answer: '+(a||'(blank)')+'\nCorrect answer: '+q.answer+'\nResult: '+(ok?'Correct':'Incorrect'))});let pct=Math.round(score/questions.length*100);let name=document.getElementById('studentName').value.trim()||'Student';let submitted=new Date().toLocaleString();lastResultText=name+' completed '+cfg('quizTitle','Math Quiz')+'.\nScore: '+score+'/'+questions.length+'\nPercentage: '+pct+'%\nSubmitted: '+submitted+'\nQuestions to review: '+(wrong.length?wrong.join(', '):'None')+'\n\n'+details.join('\n\n---\n\n');let rb=document.getElementById('resultBox');rb.style.display='block';rb.innerHTML='<h2>'+esc(name)+' Result</h2><p><b>Score:</b> '+score+'/'+questions.length+'</p><p><b>Percentage:</b> '+pct+'%</p><p><b>Questions to review:</b> '+(wrong.length?wrong.join(', '):'None')+'</p><div id="status" class="status">Sending result...</div>';await sendResult(name,score,pct,submitted,wrong)}
async function sendResult(name,score,pct,submitted,wrong){let st=document.getElementById('status');let key=cfg('web3formsAccessKey','');let email=cfg('parentEmail','');if(!key){st.innerHTML='Web3Forms key is missing in config.js. Result is graded but not emailed.';return}let payload={access_key:key,subject:'Shayan Math Quiz Result',from_name:'Shayan Quiz',name:name,email:email,message:lastResultText,score:score+'/'+questions.length,percentage:pct+'%',submitted_at:submitted,questions_to_review:wrong.length?wrong.join(', '):'None'};try{let r=await fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});let data=await r.json();if(r.ok&&data.success){st.textContent='Result submitted through Web3Forms. Check email inbox/spam.'}else{st.textContent='Web3Forms rejected submission: '+(data.message||'Unknown error')}}catch(err){st.textContent='Could not connect to Web3Forms: '+err.message}}
function showAnswers(){questions.forEach((q,i)=>{let f=document.getElementById('feedback-'+i);f.className='feedback correct';f.textContent='Answer: '+q.answer+'. '+(q.explanation||'')})}
loadQuestions();
